import "@/styles/globals.css";
import { NextComponentType, NextPageContext } from "next";
import type { AppProps } from "next/app";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";

import Navbar from "@/components/Navbar";
import ProtectedRoute from "@/components/ProtectedRoute";

interface IApp extends AppProps {
  Component: NextComponentType<NextPageContext, any, any> & {
    title?: string;
    requireAuth?: boolean;
  };
}
export default function App({ Component, pageProps }: IApp) {
  const { title } = Component;

  return (
    <SessionProvider session={pageProps.session}>
      <Head>
        <title>{title || "NEXTts"}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjs, typescript, tailwind" />
        <meta name="author" content="khunnoo" />
        <meta name="description" content="Generated by khunnoo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {Component.requireAuth ? (
        <ProtectedRoute>
          <Component {...pageProps} />
        </ProtectedRoute>
      ) : (
        <Component {...pageProps} />
      )}
    </SessionProvider>
  );
}
