import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { NextComponentType, NextPageContext } from "next";

interface MyAppProps extends AppProps {
  Component: NextComponentType<NextPageContext, any, any> & {
    title?: string;
  };
}
export default function App({ Component, pageProps }: MyAppProps) {
  const { title } = Component;

  return (
    <>
      <Head>
        <title>{title || "NEXTts"}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjs, typescript, tailwind" />
        <meta name="author" content="khunnoo" />
        <meta name="description" content="Generated by khunnoo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}
