import Head from "next/head";

interface ILayout {
  title?: string;
  children: React.ReactNode;
}

export default function Layout(props: ILayout) {
  return (
    <>
      <Head>
        <title>{props.title || "Next TypeScript"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </>
  );
}
